apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
  labels:
    app.kubernetes.io/component: vlsingle
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.52.0
spec:
  image:
    tag: v1.52.0
  port: '9428'
  replicaCount: 1
  retentionPeriod: '1'
  storage:
    accessModes:
    - ReadWriteOnce
    storageClassName: openebs-hostpath
    resources:
      requests:
        storage: 20Gi
