apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-k8s-stack-grafana-ds
  namespace: monitoring
  labels:
    grafana_datasource: '1'
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.147.0
data:
  datasource.yaml: "apiVersion: 1\ndatasources: \n  - access: proxy\n    isDefault:\
    \ true\n    name: VictoriaMetrics\n    type: prometheus\n    uid: VictoriaMetrics\n\
    \    url: http://vmsingle-victoria-metrics-k8s-stack.monitoring.svc.cluster.local.:8428\n\
    \  - access: proxy\n    isDefault: false\n    name: VictoriaMetrics (DS)\n   \
    \ type: victoriametrics-metrics-datasource\n    uid: VictoriaMetricsDS\n    url:\
    \ http://vmsingle-victoria-metrics-k8s-stack.monitoring.svc.cluster.local.:8428\n\
    \  - access: proxy\n    isDefault: false\n    name: VictoriaLogs (DS)\n    type:\
    \ victoriametrics-logs-datasource\n    uid: VictoriaLogs\n    url: http://vlsingle-victoria-metrics-k8s-stack.monitoring.svc.cluster.local.:9428\n\
    \  - access: proxy\n    jsonData:\n      implementation: prometheus\n    name:\
    \ Alertmanager\n    type: alertmanager\n    uid: Alertmanager\n    url: http://vmalertmanager-victoria-metrics-k8s-stack.monitoring.svc.cluster.local.:9093"
