apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoria-metrics-k8s-stack-sync-job
  namespace: monitoring
  labels:
    app.kubernetes.io/component: syncJob
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v0.0.11
