---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-proxmox
  namespace: homepage
spec:
  encryptedData:
    proxmox.yaml: AgBPhrXwgziV0lqoqLpQOwu56dCRConxd/pNKky/hmx5il9w3c93ZcRoDugBVZkwHUBLDyQB6CW3HJpa8FaecMnnzqh8SuzbR7YzWjoBlWiqDvPGewnk9ze9wZBTtcsdwfGU0HeTW+UNe4AczQsT+acQnK5TZ9z1oYUOxvkfJZWySSj9Jz/UE8uVUA9cg2sK353l8JsbP0fVFJl+zdBdP5tYuFxQR5Dn/rwOmKYrHq8ZWTMd0V1CIer01BOR1jAzjj+vxMSLn35VAtdFoviN7LXEL9kMrVct7Ti8JKbwjx7vJxQlz6JGQIj3eHV9CwcjeYzWAtuTUHy2hbJhYWjzmtUXlQCE6eMH51PvF653bOz+Mnd57JIYI/hP5cx9aiH/gFFo/+Gy4UgoZfwN1Tsp/Vxqn1E3763yuYovaWlNc5Oq1oqiLQwMbeSZ1rXay5TstS+puq4mchN1ZdHn/Z5ySwePxqyldHnn3T8Q5frsT2pK3Qt9+w5Au7Cu7QdG41BafbPFRa6/0Ex8YBpwWM6LAHfKIEsLgBawjej0WMderXQ0a+belcY0UQqphb/6hRO0nc3JMANNwYxwdJ2X65bvdOQYNl1iW9kvDJeMx/n6FvyvY9PbyFQTgJQPqhpFeqf5Lsm+x3JxK4YvdQrMp5htbSqUkrIfA4Fj2AiJDsXrG+rIqQa0HnDbw8Fmnq2zbHbdHPcewa7+FH4CVQcS5M9GXmcdsd/+DiR5FLY34POwzdCi2NWaJjd0z7eF8+lgZVchxCAzDIaePuJ1R17qm330plFZSlNrkNsdEGBboqrq7IDxP6y8Wgn9VBHVnMhAIBhrwoh6NeNiZ1Yr2XTLfT/X/hsiILM=
  template:
    metadata:
      name: homepage-proxmox
      namespace: homepage
    type: Opaque
