apiVersion: v1
data:
  admin-password: NlI4dVEwYm5uSkwyODAzT05uMlYyR0JZSEU3aHFHTU04RGxjSmV3Zg==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  creationTimestamp: "2026-07-18T16:38:41Z"
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 13.1.0
  name: grafana
  namespace: monitoring
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: grafana
    uid: e5260e99-63b3-4a4d-9eb9-340dfb62bb1b
  resourceVersion: "57769800"
  uid: 379088cc-e8f3-4eef-a1e9-7f7eccf482c2
type: Opaque
