apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: homelab-authelia
    app.kubernetes.io/version: 4.38.16
data:
  users-database.yml: |
    ---
    users:
      authelia:
        disabled: false
        displayname: "Authelia User"
        # Password is authelia
        password: "$6$rounds=50000$BpLnfgDsc2WD8F2q$Zis.ixdg9s/UOJYrs56b5QEZFiZECu0qZVNsIYxBaNJ7ucIL.nlxVCT5tqh8KHG8X4tlwCFm5r6NTOZZ5qRFN/"  # yamllint disable-line rule:line-length
        email: authelia@authelia.com
        groups:
          - admins
          - dev
    ...

