apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: homelab-authelia
    app.kubernetes.io/version: 4.38.16
data:
  users-database.yml: |
    ---
    users:
      authelia:
        disabled: false
        displayname: "Authelia User"
        password: "$6$rounds=50000$BpLnfgDsc2WD8F2q$Zis.ixdg9s/UOJYrs56b5QEZFiZECu0qZVNsIYxBaNJ7ucIL.nlxVCT5tqh8KHG8X4tlwCFm5r6NTOZZ5qRFN/"  # yamllint disable-line rule:line-length
        email: edward.heaver01+authelia@gmail.com
        groups:
          - admins
          - dev

      edwardheaver:
        disabled: false
        displayname: "Edward Heaver"
        password: "$argon2id$v=19$m=65536,t=3,p=4$Mvn405S13axgZaQ3vCKctA$kT/5LyZ6qqRkG5O5RCn3gTSh1ojhwvbZTg5Lw6fG4YQ"  # yamllint disable-line rule:line-length
        email: edward.heaver01@gmail.com
        groups:
          - admins
          - dev
    ...

