apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodpecker-cache
  namespace: woodpecker
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard