kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: victoria-metrics-operator
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/version: v0.73.1
subjects:
- kind: ServiceAccount
  name: victoria-metrics-operator
  namespace: monitoring
roleRef:
  kind: Role
  name: victoria-metrics-operator
  apiGroup: rbac.authorization.k8s.io
