---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vmalertmanager-victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgAcdF/ZAOivUgL1ws57PwaCr2rpXTMf+34ji0KfW2VgCfqnBLpW9pUUs+67qNVvB3H/g8ktFjoTGFUO2A+ZD084bazMS1X9fjPkuFJld3jKEACzgvNIfuRbASgcShanx6ZuwkIXz74M8koHoQ3LV7gOqFcg3xaEUOxyGH4c0GG3fmFtC54t4l6cS65U+sU0p7Pjk3o1b3w7Sbo+axu2gUWkiUatYkPGRYMBdmaUSVOjnPLxldjCKlgTaOHM4u2OLBc7w/YLQz4zYY9CY7Bkpr+WrtgP3+eqKxFGrJYKe8Su0mQCq+soIRN3ua5PQhr4sz5SpgOK5y8W33DuS6BEKMkEbYtC+hKaEQZEyQgrYGZumRohj+Ul8PPn+pOXndtikMIQEMcqaVJDNWP9sLBANQjZalejYF4GX2J1fAsxPdMWbQmTTNL968sOC5Fvqkb1xD9LuV7D+fb256ScAKmFHtpkQ3aSNwWxNig/5Hh//21wvcdmC6M4gkgTMnyPPOtE1toBz1GkxL3TBMRFe1z4BNIrN2UYOMhpAl/fSb2UA7EHA1h89STilLlsYol0AtNr69LwB6M55ukJ6HUDt899QYct4JZSteOgaOxoRfTKsxdrFyQUL6YvXCmif0wxCffE//mSuo8D3EG8Yc20a554J3txVrmdJymbOGejIdFCVCR3oqYC1LJM7ecBJKhXF5SnMTtC3JXkTy8p5RcQKh0RRKYoPt/MNiKj3Nz/nQ4sumnkKIUbFNoW3pwUv0SADJSSPlODxwoxuVhvjMFF5YzJJG0E6O0n0ridp/o8IX6NvkHgZt3fJBd81EccP+v5RGiMAO5R8w==
  template:
    metadata:
      labels:
        app.kubernetes.io/component: alertmanager
        app.kubernetes.io/instance: victoria-metrics
        app.kubernetes.io/name: victoria-metrics-k8s-stack
        app.kubernetes.io/version: v0.32.1
      name: vmalertmanager-victoria-metrics-k8s-stack
      namespace: monitoring
