apiVersion: v1
kind: Service
metadata:
  name: http-echo-svc
  namespace: test
spec:
  selector:
    app: http-echo
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 8080
    - name: web-secure
      port: 443
      targetPort: 8443
