apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml
- ./kube-state-metrics/serviceaccount-kube-state-metrics.yaml
- ./node-exporter/serviceaccount-prometheus-node-exporter.yaml
- ./operator/serviceaccount-victoria-metrics-operator-cleanup-hook.yaml
- ./operator/serviceaccount-victoria-metrics-operator.yaml
- ./sync-job/serviceaccount-victoria-metrics-k8s-stack-sync-job.yaml
- ./sync-job/configmap-victoria-metrics-k8s-stack-sync-job-config.yaml
- ./vm/configmap-vmalertmanager-victoria-metrics-k8s-stack-monzo-tpl.yaml
- ./secrets/sealed-victoria-metrics-operator-validation.yaml
- ./secrets/sealed-vmalertmanager-victoria-metrics-k8s-stack.yaml
- ./kube-state-metrics/clusterrole-kube-state-metrics.yaml
- ./operator/clusterrole-victoria-metrics-operator-cleanup-hook.yaml
- ./operator/clusterrole-victoria-metrics-operator-victoriametrics-admin.yaml
- ./operator/clusterrole-victoria-metrics-operator-victoriametrics-view.yaml
- ./operator/clusterrole-victoria-metrics-operator.yaml
- ./kube-state-metrics/clusterrolebinding-kube-state-metrics.yaml
- ./operator/clusterrolebinding-victoria-metrics-operator-cleanup-hook.yaml
- ./operator/clusterrolebinding-victoria-metrics-operator.yaml
- ./operator/role-victoria-metrics-operator.yaml
- ./sync-job/role-victoria-metrics-k8s-stack-sync-job.yaml
- ./operator/rolebinding-victoria-metrics-operator.yaml
- ./sync-job/rolebinding-victoria-metrics-k8s-stack-sync-job.yaml
- ./kube-state-metrics/service-kube-state-metrics.yaml
- ./node-exporter/service-prometheus-node-exporter.yaml
- ./operator/service-victoria-metrics-operator.yaml
- ./vm/service-victoria-metrics-k8s-stack-core-dns.yaml
- ./vm/service-victoria-metrics-k8s-stack-kube-controller-manager.yaml
- ./vm/service-victoria-metrics-k8s-stack-kube-etcd.yaml
- ./vm/service-victoria-metrics-k8s-stack-kube-scheduler.yaml
- ./node-exporter/daemonset-prometheus-node-exporter.yaml
- ./kube-state-metrics/deployment-kube-state-metrics.yaml
- ./operator/deployment-victoria-metrics-operator.yaml
- ./operator/validatingwebhookconfiguration-victoria-metrics-operator-admission.yaml
- ./vm/vmagent-victoria-metrics-k8s-stack.yaml
- ./vm/vmalert-victoria-metrics-k8s-stack.yaml
- ./vm/vmalertmanager-victoria-metrics-k8s-stack.yaml
- ./vm/vmsingle-victoria-metrics-k8s-stack.yaml
- ./vm/vmnodescrape-victoria-metrics-k8s-stack-cadvisor.yaml
- ./vm/vmnodescrape-victoria-metrics-k8s-stack-kubelet.yaml
- ./vm/vmnodescrape-victoria-metrics-k8s-stack-probes.yaml
- ./vm/vmnodescrape-victoria-metrics-k8s-stack-resources.yaml
- ./operator/vmservicescrape-victoria-metrics-operator.yaml
- ./vm/vmservicescrape-victoria-metrics-k8s-stack-core-dns.yaml
- ./vm/vmservicescrape-victoria-metrics-k8s-stack-grafana.yaml
- ./vm/vmservicescrape-victoria-metrics-k8s-stack-kube-api-server.yaml
- ./vm/vmservicescrape-victoria-metrics-k8s-stack-kube-controller-manager.yaml
- ./vm/vmservicescrape-victoria-metrics-k8s-stack-kube-etcd.yaml
- ./vm/vmservicescrape-victoria-metrics-k8s-stack-kube-scheduler.yaml
- ./vm/vmservicescrape-victoria-metrics-k8s-stack-kube-state-metrics.yaml
- ./vm/vmservicescrape-victoria-metrics-k8s-stack-prometheus-node-exporter.yaml
- ./operator-cleanup/job-victoria-metrics-operator-cleanup-hook.yaml
- ./sync-job/job-victoria-metrics-k8s-stack-sync-job.yaml
