apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mcp-fetch-certificate
  namespace: toolhive-system
spec:
  commonName: "eheaver.cloud"
  secretName: default-ingress-cert
  issuerRef:
    name: internal-cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "eheaver.cloud"
    - "fetch.internal.eheaver.cloud"