apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mcp-fetch
  namespace: toolhive-system

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`fetch.internal.eheaver.cloud`)
      priority: 10
      services:
        - kind: Service
          name: mcp-fetch-proxy
          namespace: toolhive-system
          port: 8080
      middlewares:
        - name: redirect-https
          namespace: kube-system
  tls:
    secretName: mcp-fetch-certificate-secret