apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: ehmcpservers.eheaver.cloud
spec:
  group: eheaver.cloud
  names:
    kind: EHMCPServer
    plural: ehmcpservers
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                mcpSettings:
                  type: object
                  properties:
                    transport:
                      type: string
                      default: sse
                    port:
                      type: integer
                      default: 80
                ingressSettings:
                  type: object
                  properties:
                    port:
                      type: integer
                      default: 8080
                    domain:
                      type: string
