apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls
  namespace: homepage
spec:
  commonName: "eheaver.cloud"
  secretName: homepage-cert-secret
  privateKey:
    rotationPolicy: "Never"
  issuerRef:
    name: internal-cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "eheaver.cloud"
    - "*.eheaver.cloud"
    - "*.internal.eheaver.cloud"
