apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/version: "v1.13.2"
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
    headerStyle: boxedWidgets
    layout:
      Monitoring & Metrics:
        style: row
        columns: 2
      AI:
        style: row
        columns: 2
      Infrastructure:
        style: row
        columns: 2
  bookmarks.yaml: |
    - Homelab:
        - GitHub:
            - abbr: GH
              href: https://github.com/Captainmango
  services.yaml: |
    - Monitoring & Metrics:
        - Grafana:
            href: https://grafana.eheaver.cloud
            description: Metrics dashboards
            icon: grafana.png
        - Traefik (K8s Ingress):
            href: https://traefik.internal.eheaver.cloud
            description: Ingress controller dashboard
            icon: traefik.png

    - Homelab K8s Nodes:
        - K0s Controller:
            href: https://proxmox.eheaver.cloud/
            description: k0s controller node
            icon: https://cncf-icons.com/artwork/projects/k0s/horizontal/color/k0s-logo-2025-horizontal.svg
            proxmoxNode: pve
            proxmoxVMID: 1001
        - K0s Worker 1:
            href: https://proxmox.eheaver.cloud/
            description: k0s worker node 1
            icon: https://cncf-icons.com/artwork/projects/k0s/horizontal/color/k0s-logo-2025-horizontal.svg
            proxmoxNode: pve
            proxmoxVMID: 2001
        - K0s Worker 2:
            href: https://proxmox.eheaver.cloud/
            description: k0s worker node 2
            icon: https://cncf-icons.com/artwork/projects/k0s/horizontal/color/k0s-logo-2025-horizontal.svg
            proxmoxNode: pve
            proxmoxVMID: 2002

    - AI Tools:
        - Open WebUI:
            href: https://chat.eheaver.cloud
            description: Chat interface
            icon: open-webui.png
        - LiteLLM:
            href: https://litellm.eheaver.cloud
            description: LLM proxy
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/litlellm.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
  custom.css: ""
  custom.js: ""
