apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - role: controller
    ssh:
      address: 192.168.100.11
      user: ubuntu
      port: 22
      keyPath: "~/.ssh/id_rsa"
      bastion:
        address: 192.168.1.162
        user: ubuntu
        keyPath: "~/.ssh/id_rsa"
  - role: worker 
    ssh:
      address: 192.168.100.21
      user: ubuntu
      port: 22
      keyPath: "~/.ssh/id_rsa"
      bastion:
        address: 192.168.1.162
        user: ubuntu
        keyPath: "~/.ssh/id_rsa"
  - role: worker 
    ssh:
      address: 192.168.100.22
      user: ubuntu
      port: 22
      keyPath: "~/.ssh/id_rsa"
      bastion:
        address: 192.168.1.162
        user: ubuntu
        keyPath: "~/.ssh/id_rsa"
        
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false

